// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// countZeroes
int countZeroes(Rcpp::IntegerVector x);
RcppExport SEXP _introRcppSugar_countZeroes(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(countZeroes(x));
    return rcpp_result_gen;
END_RCPP
}
// countZeroesSugar
int countZeroesSugar(IntegerVector x);
RcppExport SEXP _introRcppSugar_countZeroesSugar(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(countZeroesSugar(x));
    return rcpp_result_gen;
END_RCPP
}
// fonction_sucree
double fonction_sucree(NumericVector x, NumericVector y);
RcppExport SEXP _introRcppSugar_fonction_sucree(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fonction_sucree(x, y));
    return rcpp_result_gen;
END_RCPP
}
// pi_sugar
double pi_sugar(const int N);
RcppExport SEXP _introRcppSugar_pi_sugar(SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(pi_sugar(N));
    return rcpp_result_gen;
END_RCPP
}
// pi_boucle
double pi_boucle(const int N);
RcppExport SEXP _introRcppSugar_pi_boucle(SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(pi_boucle(N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_introRcppSugar_countZeroes", (DL_FUNC) &_introRcppSugar_countZeroes, 1},
    {"_introRcppSugar_countZeroesSugar", (DL_FUNC) &_introRcppSugar_countZeroesSugar, 1},
    {"_introRcppSugar_fonction_sucree", (DL_FUNC) &_introRcppSugar_fonction_sucree, 2},
    {"_introRcppSugar_pi_sugar", (DL_FUNC) &_introRcppSugar_pi_sugar, 1},
    {"_introRcppSugar_pi_boucle", (DL_FUNC) &_introRcppSugar_pi_boucle, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_introRcppSugar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
