# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countZeroes <- function(x) {
    .Call(`_introRcppSugar_countZeroes`, x)
}

countZeroesSugar <- function(x) {
    .Call(`_introRcppSugar_countZeroesSugar`, x)
}

fonction_sucree <- function(x, y) {
    .Call(`_introRcppSugar_fonction_sucree`, x, y)
}

pi_sugar <- function(N) {
    .Call(`_introRcppSugar_pi_sugar`, N)
}

pi_boucle <- function(N) {
    .Call(`_introRcppSugar_pi_boucle`, N)
}

